# Basic pipeline example
trigger:
- main

pool:
  vmImage: 'ubuntu-24.04'

steps:
- script: echo Hello, Azure Pipelines!
  displayName: 'Run a one-line script'

- script: |
    python --version
    echo Checking python version
  displayName: 'Python version check script'
