# Basic pipeline example
trigger:
- main

pool:
  vmImage: 'ubuntu-24.04'

steps:
- script: |
    echo Checking docker version
    docker --version
  displayName: 'Docker version check script'

- script: |
    echo Checking python version
    python --version
  displayName: 'Python version check script'
